### ISSUE TITLE
What are EPICS channels ?

### ISSUE THREAD

**Issue by andreas-kupries** [auriocus/AsynCA#1]

**Comment by auriocus** [comment]
EPICS is an infrastructure for instrument control of mostly large experimental facilities [http://aps.anl.gov/epics/](http://aps.anl.gov/epics/). I'm improving on the README now.

**Comment by andreas-kupries** [comment]
Thank you for the link. That looks nice.

**Comment by auriocus** [comment]
I have enhanced the README.md file with a link to EPICS and some sample code for usage of AsynCA. Therefore I consider the issue closed. 
In principle, EPICS can be tested on a local installation with no real devices by downloading and compiling EPICS base. It makes more sense, of course, at an installation with real devices. Existing Tcl bindings are either outdated and incompatible with recent Tcl (et_wish) or do not implement all asynchronous APIs (epicstcl). None of them provides bindings to the server side of EPICS.
